config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create]
  resources :lists do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :rating, inclusion: { in: (1..5) }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
   before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @review = Review.new
    @bookmark = Bookmark.new
    @review.list = @list
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[create]

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    @review.save
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h2>Add Movie to list</h2>
<hr>
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Syne:wght@400..800&display=swap" rel="stylesheet">
  </head>

  <body>

  <%# Navbar %>
  <div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://www.creativefabrica.com/wp-content/uploads/2019/03/Monogram-RM-Logo-Design-by-Greenlines-Studios.jpg" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", lists_path, class: "nav-link text-danger fw-bolder mr-1" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link text-danger fw-bolder"  %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://i.redd.it/chainsaw-man-denji-headshot-pixel-art-by-me-v0-an1fgzvculga1.png?width=2500&format=png&auto=webp&s=40c0a0fab7c7decd83fbfb4e5c2753642e695efe" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="https://www.imdb.com/?ref_=nv_home">IMDB</a>
              <a class="dropdown-item" href="https://www.movierankings.net/random">Random Movie Generator</a>
              <%# <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a> %>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/free-photo/dark-vip-cinema-studio-still-life_23-2149500593.jpg?semt=ais_hybrid&w=740);">
  <div class="container">
    <h1 class="text-danger"><strong>R-Rated Movies</strong></h1>
    <p>Your list of movies. Your choice. Your regret!</p>
    <%= link_to "Create New List", new_list_path, class: "btn btn-dark" %>
  </div>
</div>



<div class="container d-flex">
    <div class="row">
    <% list_count = 0 %>
    <% @lists.each do |list| %>

        <div class="col-sm-6">
          <%= link_to list_path(list.id), class: "text-decoration-none" do %>
            <div class="card text-black m-2 border-light shadow p-3 mb-5 bg-body rounded">
              <%= cl_image_tag list.photo.key, class: "card-img-top" %>
              <div class="card-body">
                <h3 class="card-title text-center mt-1"><%= list.name %></h3>
              </div>
            </div>
          <% end %>
        </div>
    <% end %>

  </div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/free-photo/dark-vip-cinema-studio-still-life_23-2149500593.jpg?semt=ais_hybrid&w=740);">
  <div class="container">
    <div class="d-flex justify-content-center p-2 bg-danger" id="page-header">
      <h1 class="text-light fs-1 fw-bold font-monospace"><%= @list.name %></h1>
    </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="cards-container">
        <% @list.bookmarks.each do |bookmark| %>
            <div class="card border-dark mb-3 ms-4 mt-4 shadow">
              <%= image_tag(bookmark.movie.poster_url, class: "card-img-top") %>
              <div class="card-body">
                <h5 class="card-title"><%=  bookmark.movie.title %> | <%= bookmark.movie.rating  %> <i class="fa-solid fa-star"></i> </h5>
                <p class="card-text mb-2"><%= bookmark.movie.overview %></p>
                <div class="d-flex justify-content-between align-items-center mt-4 mb-0">
                  <div>
                    <p class="card-text text-muted fs-6 fst-italic border-dark"> <i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></p>
                  </div>
                  <div>
                    <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                      <i class="fa-solid fa-trash link-dark"></i>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-4 mt-4">
      <h5> Add a Movie: </h5>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

<hr class="shadow">

<div class="container">
  <div class="row">

    <div class="col-8">
      <div class="card border-0 me-4">
        <ul class="list-group list-group-flush">
          <% @list.reviews.each do |review| %>
            <li class="list-group-item border-bottom mb-3">
              <div class="d-flex">
                <p>
                <% review.rating.times do %>
                  <i class="fa-solid fa-star"></i>
                <% end %>
                </p>
                <p class="text-muted ms-2"> <%= time_ago_in_words(review.created_at) %> ago </p>
              </div>
              <p><%= review.comment %></p>
              <p>
            </li>
            <% end %>
        </ul>
      </div>
    </div>

    <div class="col-4 mt-4">
      Leave review:
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating %>
        <%= f.submit %>
      <% end %>
    </div>

  </div>
</div>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>